# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: lily58_dongle_pro_micro dongle_display
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"lily58Dongle_P\"
    artifact-name: nice_lily58_dongle_oled
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: lily58_left_peripheral oled_adapter_pro_micro_128x32
    # snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: lily58_right oled_adapter_pro_micro_128x32
  - board: nice_nano_v2
    shield: settings_reset
